spring:
  main:
    banner-mode: off

  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}

  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

logging:
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG

jwt:
  secret:
    access: ${jwt.secret.access}
    refresh: ${jwt.secret.refresh}

app:
  server:
    url: ${app.server.url}

redis:
  username: ${redis.username}
  password: ${redis.password}
  host: ${redis.host}
  port: ${redis.port}
