spring:
  main:
    banner-mode: off

  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}

  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

logging:
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG

jwt:
  secret:
    access: OjGsqcDSjU3qmXt6kZVzNtS4UylQGG/NC1MJK42FqnpWfhgwe/R7nIPXr0UIxipW3+lWDRLQELLvzTOaOK8QKw==
    refresh: lMgIw38fXVVZnQapAqp6Oi3F9W55akHY2mZKpp4ZmajvAjnrg61zUX+m5HsNgqEvhv0WDuW2SRYkWR16Z0Ho2w==

app:
  server:
    url: ${app.server.url}